name: dream
description: A new Flutter application.

version: 6.7.6+63

environment:
  sdk: ">=2.19.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.2.8
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.3
  audio_session: ^0.1.13
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_messaging: ^14.4.1
  firebase_storage: ^11.1.1
  firebase_database: ^10.1.1
  flutter_countdown_timer: ^4.1.0
  flutter_sound: ^9.2.13
  flutter_styled_toast: ^2.1.3
  google_mobile_ads: ^3.0.0
  intl: ^0.17.0
  just_audio: ^0.9.32
  numberpicker: ^2.1.2
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  shared_preferences: ^2.1.0
  shrink_sidemenu: ^2.0.0+2-null-safety
  unique_identifier: ^0.3.0
  localization: ^2.1.0
  circular_countdown_timer: ^0.2.3
  dropdown_button2: ^2.1.0
  http: ^0.13.6
  flutter_fortune_wheel: ^1.2.0
  package_info_plus: ^3.1.2
  social_share: ^2.3.1
  flutter_share_me: ^1.4.0
  in_app_purchase: ^3.1.5
  mobile_chat_ui: ^0.0.7
  elegant_notification: ^1.9.1
  google_sign_in: ^6.1.0
  flutter_local_notifications: ^14.0.0+1
  timezone: ^0.9.2
  pointycastle: ^3.7.3
  convert: ^3.1.1
  language_picker: ^0.4.3
  flutter_phoenix: ^1.0.0
  unity_ads_plugin: ^0.3.8



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/images/ic-modified.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/len/

  fonts:
    - family: arb
      fonts:
        - asset: assets/fonts/arb.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700